name: default

on: [ push ]

jobs:
  # --------------------------------------------------------------------------------
  # Test stage
  # --------------------------------------------------------------------------------
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install test framework
        run: go install gotest.tools/gotestsum@latest
      - name: Test
        env:
          POSTGRES_URL: "postgres://test:test@localhost:5432/postgres?sslmode=disable"
          ENV: test
        run: gotestsum --packages="./..." --junitfile report.xml --format pkgname -- -count=1 -p 1 -v -coverpkg=./...
